name: Readme update

on:
  workflow_dispatch:
  schedule:
  - cron:  '0 0 1 * *'

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
    - name: Setup variables
      id: vars
      run: |
        echo "::set-output name=datetime::$(date +'%Y_%m_%d_%H_%M')"
        echo "::set-output name=pr_branch_name::readme_update_$(date +'%Y_%m_%d_%H_%M')"
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
          python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Update readme
      run:  python manager.py generate_readme
    - name: Create PR for readme update
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Update readme for ${{ steps.vars.outputs.datetime }}
        title: Update readme | ${{ steps.vars.outputs.datetime }}
        body: |
          Update readme
          Time: ${{ steps.vars.outputs.datetime }}
        branch: ${{ steps.vars.outputs.pr_branch_name }}
        base: main
